### ISSUE TITLE
iets betere navigatie bij calculeren

### ISSUE THREAD

**Issue by TristanKatte** [Anna-Kyra/fix-the-flow-interactive-website#8]
opnieuw calculeren heeft een verwarrende navigatie

**Comment by Anna-Kyra** [comment]
![WhatsApp Image 2023-12-20 at 11 30 07](https://github.com/Anna-Kyra/fix-the-flow-interactive-website/assets/144000242/c3ff9043-0f20-462a-b0e9-5fd1b52f3f2c)

Heb de 'opnieuw calculeren button' in de nav bar gezet voor een beter call to action en de stakeholders bij elkaar in een groep gezet. Daarnaast wil ik boven  in de pagina navigatie zetten van waar je bent en waar je vandaan komt.
