### ISSUE TITLE
Calculeer button

### ISSUE THREAD

**Issue by DaanCarst** [Anna-Kyra/fix-the-flow-interactive-website#9]
Kijk of je de calculeer button kunt verplaatsen naar de nav bar.

**Comment by Anna-Kyra** [comment]
![WhatsApp Image 2023-12-20 at 11 30 07](https://github.com/Anna-Kyra/fix-the-flow-interactive-website/assets/144000242/ce011092-4dfd-426e-8171-a66820da4257)

Heb de 'opnieuw calculeren button' in de nav bar gezet voor een beter call to action en de stakeholders bij elkaar in een groep gezet.
